version: "3"

services:
  ticker-press-api:
    build:
      context: .
    ports:
      - "9000:9000"
    depends_on:
      - ticker-press-db
    volumes:
      - .:/app
  ticker-press-db:
    image: postgres:latest
    environment:
      POSTGRES_PORT: ${DB_CONFIG_PORT}:5432
      POSTGRES_USER: ${DB_CONFIG_USERNAME}
      POSTGRES_PASSWORD: ${DB_CONFIG_PASSWORD}
      POSTGRES_DB: ${DB_CONFIG_DATABASE}
    ports:
      - 5432:${DB_CONFIG_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
